(function(g){var window=this;var Qza=function(a,b){return g.Kb(a,b)},a6=function(a,b,c){a.A.set(b,c)},b6=function(a){a6(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.E)()).toString(36));
return a},c6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.kn(a.A,b,c)},Rza=function(a,b){var c=[];
g.pk(b,function(d){try{var e=g.jo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.io(e)&&c.push(d)},a);
return c},Sza=function(a,b){var c=Rza(a,b);
(0,g.y)(c,function(d){g.jo.prototype.remove.call(this,d)},a)},Tza=function(a){if(a.dd){if(a.dd.locationOverrideToken)return{locationOverrideToken:a.dd.locationOverrideToken};
if(null!=a.dd.latitudeE7&&null!=a.dd.longitudeE7)return{latitudeE7:a.dd.latitudeE7,longitudeE7:a.dd.longitudeE7}}return null},Uza=function(a,b){g.fb(a,b)||a.push(b)},d6=function(a){var b=0,c;
for(c in a)b++;return b},Vza=function(a,b){var c=b instanceof g.Ac?b:g.Gc(b,/^data:image\//i.test(b));
a.src=g.Bc(c)},e6=function(){},Wza=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Xza=function(a){if(a.Wd&&"function"==typeof a.Wd)return a.Wd();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Gb(a)},Yza=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.gf&&"function"==typeof a.gf)var c=a.gf();else if(a.Wd&&"function"==typeof a.Wd)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Hb(a);d=Xza(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Zza=function(a,b,c,d){var e=new g.Ym(null,void 0);
a&&g.Zm(e,a);b&&g.$m(e,b);c&&g.an(e,c);d&&(e.u=d);return e},f6=function(a,b){g.Qo[a]=!0;
var c=g.Oo();c&&c.publish.apply(c,arguments);g.Qo[a]=!1},g6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Vm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",$za(this,a.capabilities||""),aAa(this,a.experiments||""))},$za=function(a,b){a.capabilities.clear();
(0,g.Ce)(b.split(","),g.Sa(Qza,bAa)).forEach(function(c){a.capabilities.add(c)})},aAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},h6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},i6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},cAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},dAa=function(a){return new h6(a)},eAa=function(a){return Array.isArray(a)?(0,g.Lc)(a,dAa):[]},j6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},k6=function(a){return Array.isArray(a)?"["+(0,g.Lc)(a,j6).join(",")+"]":"null"},l6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},fAa=function(a){return(0,g.Lc)(a,function(b){return{key:b.id,
name:b.name}})},m6=function(a,b){return g.cb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},n6=function(a,b){return g.cb(a,function(c){return i6(c,b)})},gAa=function(){var a=(0,g.Zs)();
a&&Sza(a,a.o.Wh(!0))},o6=function(){var a=g.bt("yt-remote-connected-devices")||[];
g.wb(a);return a},hAa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Lc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},iAa=function(a){g.at("yt-remote-connected-devices",a,86400)},q6=function(){if(p6)return p6;
var a=g.bt("yt-remote-device-id");a||(a=l6(),g.at("yt-remote-device-id",a,31536E3));for(var b=o6(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return p6=d},r6=function(){var a=o6(),b=q6();
g.fb(a,b);g.dt()&&g.yb(a,b);a=hAa(a);if(g.gb(a))try{g.Bq.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.Cq("remote_sid",a.join(","),-1)}catch(c){}},jAa=function(){return g.bt("yt-remote-session-browser-channel")},kAa=function(){return g.bt("yt-remote-local-screens")||[]},lAa=function(){g.at("yt-remote-lounge-token-expiration",!0,86400)},mAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Lc)(kAa(),function(d){return d.loungeToken}),c=(0,g.Lc)(a,function(d){return d.loungeToken});
(0,g.Ci)(c,function(d){return!g.fb(b,d)})&&lAa();
g.at("yt-remote-local-screens",a,31536E3)},nAa=function(a,b){g.at("yt-remote-session-browser-channel",a);
g.at("yt-remote-session-screen-id",b);var c=o6(),d=q6();g.fb(c,d)||c.push(d);iAa(c);r6()},s6=function(a){a||(g.ct("yt-remote-session-screen-id"),g.ct("yt-remote-session-video-id"));
r6();a=o6();g.kb(a,q6());iAa(a)},oAa=function(){if(!t6){var a=g.po();
a&&(t6=new g.co(a))}return t6?!!t6.get("yt-remote-use-staging-server"):!1},pAa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},qAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?rAa(a.shift(),function(){u6(a)}):v6()},sAa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},rAa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=qAa();
a&&a(!1,"No cast extension found")},uAa=function(){if(tAa){var a=2,b=qAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;rAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},vAa=function(){uAa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},w6=function(a,b,c){g.A.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Nd=b;this.C=(0,g.x)(this.NG,this);this.o=!1;this.u=0;this.A=this.Ka=null;this.B=[]},x6=function(a,b,c){g.A.call(this);
this.B=null!=c?a.bind(c):a;this.Nd=b;this.A=null;this.o=!1;this.u=0;this.Ka=null},y6=function(a){a.Ka=g.cg(function(){a.Ka=null;
a.o&&!a.u&&(a.o=!1,y6(a))},a.Nd);
var b=a.A;a.A=null;a.B.apply(null,b)},z6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Wza(a)},A6=function(){},B6=function(){},wAa=function(){},yAa=function(a){return(a=xAa(a))?new ActiveXObject(a):new XMLHttpRequest},xAa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},C6=function(a,b,c,d){this.o=a;
this.A=b;this.I=c;this.G=d||1;this.C=45E3;this.B=new g.z1(this);this.u=new g.bg;this.u.setInterval(250)},AAa=function(a,b,c){a.Pl=1;
a.Zh=b6(b.clone());a.hk=c;a.F=!0;zAa(a,null)},D6=function(a,b,c,d,e){a.Pl=1;
a.Zh=b6(b.clone());a.hk=null;a.F=c;e&&(a.zD=!1);zAa(a,d)},zAa=function(a,b){a.Kl=(0,g.E)();
E6(a);a.Ti=a.Zh.clone();c6(a.Ti,"t",a.G);a.so=0;a.fd=a.o.wt(a.o.bo()?b:null);0<a.fu&&(a.yr=new x6((0,g.x)(a.wE,a,a.fd),a.fu));a.B.ma(a.fd,"readystatechange",a.vO);var c=a.Aj?g.Rb(a.Aj):{};a.hk?(a.qs="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.fd.send(a.Ti,a.qs,a.hk,c)):(a.qs="GET",a.zD&&!g.re&&(c.Connection="close"),a.fd.send(a.Ti,a.qs,null,c));a.o.Vf(1)},DAa=function(a,b,c){for(var d=!0;!a.hj&&a.so<c.length;){var e=BAa(a,c);
if(e==F6){4==b&&(a.oi=4,G6(15),d=!1);break}else if(e==CAa){a.oi=4;G6(16);d=!1;break}else H6(a,e)}4==b&&0==c.length&&(a.oi=1,G6(17),d=!1);a.eg=a.eg&&d;d||(I6(a),J6(a))},BAa=function(a,b){var c=a.so,d=b.indexOf("\n",c);
if(-1==d)return F6;c=Number(b.substring(c,d));if(isNaN(c))return CAa;d+=1;if(d+c>b.length)return F6;var e=b.substr(d,c);a.so=d+c;return e},FAa=function(a,b){a.Kl=(0,g.E)();
E6(a);var c=b?window.location.hostname:"";a.Ti=a.Zh.clone();a6(a.Ti,"DOMAIN",c);a6(a.Ti,"t",a.G);try{a.kg=new ActiveXObject("htmlfile")}catch(n){I6(a);a.oi=7;G6(22);J6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)e+="\\x3c";else if(">"==h)e+="\\x3e";else{var l=h;if(l in K6)h=K6[l];else if(l in EAa)h=K6[l]=EAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)h=l;else{if(256>m){if(h="\\x",16>m||256<m)h+="0"}else h="\\u",4096>m&&(h+="0");h+=m.toString(16).toUpperCase()}h=
K6[l]=h}e+=h}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.cd(g.cc("b/12014412"),d+"</body></html>");a.kg.open();a.kg.write(g.Yc(c));a.kg.close();a.kg.parentWindow.m=(0,g.x)(a.KN,a);a.kg.parentWindow.d=(0,g.x)(a.DC,a,!0);a.kg.parentWindow.rpcClose=(0,g.x)(a.DC,a,!1);c=a.kg.createElement("DIV");a.kg.parentWindow.document.body.appendChild(c);d=g.Fc(a.Ti.toString());d=g.kd(g.Bc(d));d=g.cd(g.cc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.dd(c,d);a.o.Vf(1)},E6=function(a){a.ax=(0,g.E)()+a.C;
GAa(a,a.C)},GAa=function(a,b){if(null!=a.Wl)throw Error("WatchDog timer not null");
a.Wl=L6((0,g.x)(a.SN,a),b)},M6=function(a){a.Wl&&(g.v.clearTimeout(a.Wl),a.Wl=null)},J6=function(a){a.o.Ez()||a.hj||a.o.Tp(a)},I6=function(a){M6(a);
g.Oe(a.yr);a.yr=null;a.u.stop();g.sua(a.B);if(a.fd){var b=a.fd;a.fd=null;b.abort();b.dispose()}a.kg&&(a.kg=null)},H6=function(a,b){try{a.o.uC(a,b),a.o.Vf(4)}catch(c){}},IAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;HAa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){IAa(a,b,c,d,f)},f)})}},HAa=function(a,b,c){var d=new Image;
d.onload=function(){try{N6(d),c(!0)}catch(e){}};
d.onerror=function(){try{N6(d),c(!1)}catch(e){}};
d.onabort=function(){try{N6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{N6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Vza(d,a)},N6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},JAa=function(a){this.o=a;
this.u=new A6},KAa=function(a){var b=O6(a.o,a.jm,"/mail/images/cleardot.gif");
b6(b);IAa(b.toString(),5E3,(0,g.x)(a.KF,a),3,2E3);a.Vf(1)},Q6=function(a){var b=a.o.M;
if(null!=b)G6(5),b?(G6(11),P6(a.o,a,!1)):(G6(12),P6(a.o,a,!0));else if(a.ye=new C6(a,void 0,void 0,void 0),a.ye.Aj=a.du,b=a.o,b=O6(b,b.bo()?a.Om:null,a.eu),G6(5),!g.pe||g.Ud(10))c6(b,"TYPE","xmlhttp"),D6(a.ye,b,!1,a.Om,!1);else{c6(b,"TYPE","html");var c=a.ye;a=!!a.Om;c.Pl=3;c.Zh=b6(b.clone());FAa(c,a)}},R6=function(a){g.rf.call(this);
this.headers=new g.Vm;this.T=a||null;this.A=!1;this.U=this.o=null;this.fa=this.M="";this.F=0;this.B="";this.C=this.aa=this.I=this.Y=!1;this.G=0;this.N=null;this.ga="";this.R=this.Z=!1},LAa=function(a){return g.pe&&g.Td(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},MAa=function(a){return"content-type"==a.toLowerCase()},OAa=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;NAa(a);S6(a)},NAa=function(a){a.Y||(a.Y=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},QAa=function(a){if(a.A&&"undefined"!=typeof g.E1)if(a.U[1]&&4==T6(a)&&2==a.getStatus())U6(a,"Local request error detected and ignored");
else if(a.I&&4==T6(a))g.cg(a.qC,0,a);else if(a.dispatchEvent("readystatechange"),4==T6(a)){U6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.ud(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!PAa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<T6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";NAa(a)}}finally{S6(a)}}},S6=function(a,b){if(a.o){RAa(a);
var c=a.o,d=a.U[0]?g.Ka:null;a.o=null;a.U=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},RAa=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.N&&(g.v.clearTimeout(a.N),a.N=null)},T6=function(a){return a.o?a.o.readyState:0},V6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},U6=function(a,b){return b+" ["+a.fa+" "+a.M+" "+a.getStatus()+"]"},W6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new A6;this.I=a||null;this.M=null!=b?b:null;this.F=c||!1},SAa=function(a,b){this.o=a;
this.map=b;this.context=null},TAa=function(a){g.Qe.call(this,"statevent",a)},UAa=function(a,b){g.Qe.call(this,"timingevent",a);
this.size=b},VAa=function(a){g.Qe.call(this,"serverreachability",a)},YAa=function(a){WAa(a);
if(3==a.o){var b=a.xn++,c=a.Cp.clone();a6(c,"SID",a.A);a6(c,"RID",b);a6(c,"TYPE","terminate");X6(a,c);b=new C6(a,a.A,b,void 0);b.Pl=2;b.Zh=b6(c.clone());Vza(new Image,b.Zh.toString());b.Kl=(0,g.E)();E6(b)}XAa(a)},ZAa=function(a){a.lG(1,0);
a.Cp=O6(a,null,a.cu);Y6(a)},WAa=function(a){a.ci&&(a.ci.abort(),a.ci=null);
a.Dc&&(a.Dc.cancel(),a.Dc=null);a.Zg&&(g.v.clearTimeout(a.Zg),a.Zg=null);Z6(a);a.le&&(a.le.cancel(),a.le=null);a.hi&&(g.v.clearTimeout(a.hi),a.hi=null)},$Aa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new SAa(a.vK++,b));2!=a.o&&3!=a.o||Y6(a)},Y6=function(a){a.le||a.hi||(a.hi=L6((0,g.x)(a.CC,a),0),a.Pk=0)},bBa=function(a,b){if(1==a.o){if(!b){a.xn=Math.floor(1E5*Math.random());
var c=a.xn++,d=new C6(a,"",c,void 0);d.Aj=null;var e=$6(a),f=a.Cp.clone();a6(f,"RID",c);a6(f,"CVER","1");X6(a,f);AAa(d,f,e);a.le=d;a.o=2}}else 3==a.o&&(b?aBa(a,b):0==a.u.length||a.le||aBa(a))},aBa=function(a,b){if(b)if(6<a.ij){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.xn-1;var d=$6(a)}else c=b.I,d=b.hk;else c=a.xn++,d=$6(a);var e=a.Cp.clone();a6(e,"SID",a.A);a6(e,"RID",c);a6(e,"AID",a.ll);X6(a,e);c=new C6(a,a.A,c,a.Pk+1);c.Aj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.le=c;AAa(c,e,d)},X6=function(a,b){if(a.Kd){var c=a.Kd.cz();
c&&g.Ab(c,function(d,e){a6(b,e,d)})}},$6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.ij&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,h=a.u[e].map;f=6>=a.ij?e:f-d;try{g.Ab(h,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},cBa=function(a){a.Dc||a.Zg||(a.G=1,a.Zg=L6((0,g.x)(a.BC,a),0),a.Bk=0)},a7=function(a){if(a.Dc||a.Zg||3<=a.Bk)return!1;
a.G++;a.Zg=L6((0,g.x)(a.BC,a),dBa(a,a.Bk));a.Bk++;return!0},P6=function(a,b,c){a.ks=c;
a.ug=b.qh;a.F||ZAa(a)},Z6=function(a){null!=a.mj&&(g.v.clearTimeout(a.mj),a.mj=null)},dBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},b7=function(a,b){if(2==b||9==b){var c=null;
a.Kd&&(c=null);var d=(0,g.x)(a.eP,a);c||(c=new g.Ym("//www.google.com/images/cleardot.gif"),b6(c));HAa(c.toString(),1E4,d)}else G6(2);eBa(a,b)},eBa=function(a,b){a.o=0;
a.Kd&&a.Kd.ry(b);XAa(a);WAa(a)},XAa=function(a){a.o=0;
a.ug=-1;if(a.Kd)if(0==a.B.length&&0==a.u.length)a.Kd.gt();else{g.ob(a.B);var b=g.ob(a.u);a.B.length=0;a.u.length=0;a.Kd.gt(b)}},O6=function(a,b,c){var d=g.fn(c);
if(""!=d.o)b&&g.$m(d,b+"."+d.o),g.an(d,d.B);else{var e=window.location;d=Zza(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Dm&&g.Ab(a.Dm,function(f,h){a6(d,h,f)});
a6(d,"VER",a.ij);X6(a,d);return d},L6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},G6=function(a){c7.dispatchEvent(new TAa(c7,a))},fBa=function(){},gBa=function(){this.o=[];
this.u=[]},hBa=function(a,b){this.action=a;
this.params=b||{}},d7=function(a,b){g.A.call(this);
this.o=new g.G(this.DN,0,this);g.C(this,this.o);this.Nd=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.x)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},e7=function(a,b,c){this.N=a;
this.F=b;this.A=new g.bo;this.u=new d7(this.JO,this);this.o=null;this.Sc=!1;this.C=null;this.M="";this.I=this.B=0;this.G=[];this.R=c||!1},iBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ks,sessionId:a.o.A,arrayId:a.o.ll}},jBa=function(a,b){a.I=b||0;
a.u.stop();a.o&&(3==a.o.o&&bBa(a.o),YAa(a.o));a.I=0},f7=function(a){return!!a.o&&3==a.o.o},kBa=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},g7=function(a){this.scheme="https";
this.port=this.domain="";this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.ud(4,a))||"";b&&(this.port=":"+b);this.domain=g.vd(a)||"";a=g.Rc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.xc(a,"10.0")&&(this.u=!1))},h7=function(a,b){var c=a.o;
a.u&&(c=a.scheme+"://"+a.domain+a.port+a.o);return g.Fd(c+b,{})},i7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.B,d,!0),onError:g.Sa(a.A,e),Se:g.Sa(a.C,e)};c&&(a.Cb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.vq(b,a)},oBa=function(){var a=lBa;
mBa();j7.push(a);nBa(j7)},k7=function(a,b){mBa();
var c=j7,d=pBa(a,String(b));g.gb(c)?qBa(d):(nBa(c),(0,g.y)(c,function(e){e(d)}))},mBa=function(){j7||(j7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ha("yt.mdx.remote.debug.handlers_",j7,void 0))},qBa=function(a){var b=(l7+1)%50;
l7=b;m7[b]=a;n7||(n7=49==b)},nBa=function(a){var b=m7;
if(b[0]){var c=l7,d=n7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
m7=Array(50);l7=-1;n7=!1}},pBa=function(a,b){var c=((0,g.E)()-rBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},o7=function(a){g.N.call(this);
this.F=a;this.screens=[]},sBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},tBa=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.Ce)(a.screens,function(f){return!!m6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=sBa(a,b[d])||c;return c},uBa=function(a,b){var c=a.screens.length;
a.screens=(0,g.Ce)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},p7=function(a,b,c,d){g.N.call(this);
this.F=a;this.C=b;this.A=c;this.B=d;this.u=0;this.o=null;this.Ka=NaN},r7=function(a){o7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;q7(this);this.info("Initializing with "+k6(this.screens))},vBa=function(a){if(a.screens.length){var b=(0,g.Lc)(a.screens,function(d){return d.id}),c=h7(a.u,"/pairing/get_lounge_token_batch");
i7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.YG,a),(0,g.x)(a.XG,a))}},q7=function(a){var b=eAa(kAa());
b=(0,g.Ce)(b,function(c){return!c.uuid});
return tBa(a,b)},s7=function(a,b){mAa((0,g.Lc)(a.screens,cAa));
b&&lAa()},u7=function(a,b){g.N.call(this);
this.F=b;var c=g.bt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.fb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;t7("Initialized with "+g.Rk(this.o))},wBa=function(a,b,c){var d=h7(a.C,"/pairing/get_screen_availability");
i7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},v7=function(a,b){a:if(d6(b)!=d6(a.o))var c=!1;
else{c=g.Hb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(t7("Updated online screens: "+g.Rk(a.o)),a.o=b,a.S("screenChange"));xBa(a)},w7=function(a){isNaN(a.A)||g.No(a.A);
a.A=g.Lo((0,g.x)(a.Wv,a),0<a.B&&a.B<(0,g.E)()?2E4:1E4)},t7=function(a){k7("OnlineScreenService",a)},yBa=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.pc("Requesting availability of screen w/o lounge token.")});
return b},xBa=function(a){a=g.Hb(g.Bb(a.o,function(b){return b}));
g.wb(a);a.length?g.at("yt-remote-online-screen-ids",a.join(","),60):g.ct("yt-remote-online-screen-ids")},x7=function(a){o7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};zBa(this)},BBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var h=a.Me();if(h=(c?n6(h,c):null)||n6(h,b)){h.uuid=b;var l=y7(a,h);wBa(a.o,l,function(m){e(m?l:null)})}else c?ABa(a,c,(0,g.x)(function(m){var n=y7(this,new h6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));wBa(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},CBa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},ABa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Cb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.vq(h7(a.C,"/pairing/get_lounge_token_batch"),e)},DBa=function(a){a.screens=a.u.Me();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+k6(a.screens))},zBa=function(a){z7(a);
a.u=new r7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.fH,a));DBa(a);a.A=eAa(g.bt("yt-remote-automatic-screen-cache")||[]);z7(a);a.info("Initializing automatic screens: "+k6(a.A));a.o=new u7(a.C,(0,g.x)(a.Me,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=n6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.at("yt-remote-automatic-screen-cache",(0,g.Lc)(a.A,cAa)));z7(a);a.B[b.uuid]=b.id;g.at("yt-remote-device-id-map",a.B,31536E3);return b},z7=function(a){a.B=g.bt("yt-remote-device-id-map")||{}},A7=function(a,b,c){g.N.call(this);
this.U=c;this.M=a;this.o=b;this.I=null},B7=function(a,b){k7(a.U,b)},C7=function(a,b){A7.call(this,a,b,"CastSession");
this.u=null;this.A=0;this.C=(0,g.x)(this.KP,this);this.B=(0,g.x)(this.bO,this);this.A=g.Lo((0,g.x)(function(){EBa(this,null)},this),12E4)},FBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Rk(void 0));
var b={type:"getMdxSessionStatus"};a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.x)(function(){B7(this,"Failed to send message: getMdxSessionStatus.")},a)):B7(a,"Sending yt message without session: "+g.Rk(b))},EBa=function(a,b){g.No(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.kr,a),d=(0,g.x)(a.Re,a);a.xz(b,c,d,5)}}else a.Re(Error("Waiting for session status timed out."))},D7=function(a,b,c){A7.call(this,a,b,"DialSession");
this.A=this.G=null;this.N="";this.T=c;this.B=null;this.F=g.Ka;this.C=NaN;this.R=(0,g.x)(this.NP,this);this.u=g.Ka},GBa=function(a){a.u=a.M.CE(a.N,a.o.label,a.o.friendlyName,(0,g.x)(function(b){this.u=g.Ka;
this.kr(b)},a),(0,g.x)(function(b){this.u=g.Ka;
this.Re(b)},a))},HBa=function(a){var b={};
b.pairingCode=a.N;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}oAa()&&(b.env_useStageMdx=1);return g.Dd(b)},E7=function(a,b){A7.call(this,a,b,"ManualSession");
this.u=g.Lo((0,g.x)(this.nl,this,null),150)},F7=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.I=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.SM,this)},IBa=function(a,b){return b?g.cb(a.A,function(c){return i6(b,c.label)},a):null},G7=function(a){k7("Controller",a)},lBa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},H7=function(a){return a.C||!!a.A.length||!!a.o},I7=function(a,b,c){b!=a.o&&(g.Oe(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.o):a.S("yt-remote-cast2-receiver-selected",
b.o),b.subscribe("sessionScreen",(0,g.x)(a.zC,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.nl(null)):a.S("yt-remote-cast2-session-change",null))},JBa=function(a){var b=a.u.BE(),c=a.o&&a.o.o;
a=(0,g.Lc)(b,function(d){c&&i6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=IBa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},PBa=function(a,b,c,d,e,f,h){KBa()?LBa(b,e,f,h)&&(K7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?MBa(a,c):(window.__onGCastApiAvailable=function(l,m){l?MBa(a,c):(L7("Failed to load cast API: "+m),M7(!1),K7(!1),g.ct("yt-remote-cast-available"),g.ct("yt-remote-cast-receiver"),NBa(),c(!1))},d?g.Xo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?vAa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(uAa(),u6(OBa.map(sAa))))):J7("Cannot initialize because not running Chrome")},NBa=function(){J7("dispose");
var a=N7();a&&a.dispose();g.Ha("yt.mdx.remote.cloudview.instance_",null,void 0);QBa(!1);g.To(O7);O7.length=0},P7=function(){return!!g.bt("yt-remote-cast-installed")},RBa=function(){var a=g.bt("yt-remote-cast-receiver");
return a?a.friendlyName:null},SBa=function(){J7("clearCurrentReceiver");
g.ct("yt-remote-cast-receiver")},TBa=function(){return P7()?N7()?N7().getCastSession():(L7("getCastSelector: Cast is not initialized."),null):(L7("getCastSelector: Cast API is not installed!"),null)},R7=function(){P7()?N7()?Q7()?(J7("Requesting cast selector."),N7().requestSession()):(J7("Wait for cast API to be ready to request the session."),O7.push(g.So("yt-remote-cast2-api-ready",R7))):L7("requestCastSelector: Cast is not initialized."):L7("requestCastSelector: Cast API is not installed!")},S7=
function(a,b){Q7()?N7().setConnectedScreenStatus(a,b):L7("setConnectedScreenStatus called before ready.")},KBa=function(){var a=0<=g.Rc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Tw||a},UBa=function(a,b){N7().init(a,b)},LBa=function(a,b,c,d){var e=!1;
N7()||(a=new F7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.at("yt-remote-cast-available",f);f6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){J7("onReceiverSelected: "+f.friendlyName);
g.at("yt-remote-cast-receiver",f);f6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){J7("onReceiverResumed: "+f.friendlyName);
g.at("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){J7("onSessionChange: "+j6(f));
f||g.ct("yt-remote-cast-receiver");f6("yt-remote-cast2-session-change",f)}),g.Ha("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
J7("cloudview.createSingleton_: "+e);return e},N7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},MBa=function(a,b){M7(!0);
K7(!1);UBa(a,function(c){c?(QBa(!0),g.Uo("yt-remote-cast2-api-ready")):(L7("Failed to initialize cast API."),M7(!1),g.ct("yt-remote-cast-available"),g.ct("yt-remote-cast-receiver"),NBa());b(c)})},J7=function(a){k7("cloudview",a)},L7=function(a){k7("cloudview",a)},M7=function(a){J7("setCastInstalled_ "+a);
g.at("yt-remote-cast-installed",a)},Q7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},QBa=function(a){J7("setApiReady_ "+a);
g.Ha("yt.mdx.remote.cloudview.apiReady_",a,void 0)},K7=function(a){g.Ha("yt.mdx.remote.cloudview.initializing_",a,void 0)},T7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.vg=!1;this.M=this.I=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},U7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.vg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.C=0;a.u=0;a.I=0;a.M=0;a.B=NaN;a.A=!1},V7=function(a){return a.sb()?((0,g.E)()-a.F)/1E3:0},W7=function(a,b){a.G=b;
a.F=(0,g.E)()},X7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Y7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&U7(a)},Z7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Sb(a.o);b.hasPrevious=a.vg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.I;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},a8=function(a,b){g.N.call(this);
this.o=0;this.B=a;this.F=[];this.C=new gBa;this.A=this.u=null;this.M=(0,g.x)(this.bL,this);this.G=(0,g.x)(this.Bn,this);this.I=(0,g.x)(this.aL,this);this.N=(0,g.x)(this.jL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.ex,this),VBa(this))):c=3;0!=c&&(b?this.ex(c):g.Lo((0,g.x)(function(){this.ex(c)},this),0));
var d=TBa();d&&$7(this,d);this.subscribe("yt-remote-cast2-session-change",this.N)},b8=function(a){return new T7(a.B.getPlayerContextData())},VBa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Sa(this.PM,b),this))},a)},WBa=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},c8=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},e8=function(a,b,c){var d=b8(a);
W7(d,c);-1E3!=d.playerState&&(d.playerState=b);d8(a,d)},f8=function(a,b,c){a.B.sendMessage(b,c)},d8=function(a,b){WBa(a);
a.B.setPlayerContextData(Z7(b));VBa(a)},$7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Bn(null));
a.A=b;a.A&&(k7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Bn(a.A.media[0]))},XBa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=b8(a);b.contentId!=d.videoId&&k7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;W7(d,a.u.getEstimatedTime());d8(a,d)}else k7("CP","No cast media video. Ignoring state update.")},g8=function(a,b,c){return(0,g.x)(function(d){this.pc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.pc("Retrying "+b+" using MDx browser channel."),f8(this,b,c))},a)},h8=function(a,b,c){g.N.call(this);
this.C=NaN;this.R=!1;this.I=this.G=this.M=this.N=NaN;this.U=[];this.B=this.F=this.A=this.ib=this.o=null;this.Y=a;this.U.push(g.hp(window,"beforeunload",(0,g.x)(this.QG,this)));this.u=[];this.ib=new T7;this.T=b.id;this.o=YBa(this,c);this.o.subscribe("handlerOpened",this.fL,this);this.o.subscribe("handlerClosed",this.cL,this);this.o.subscribe("handlerError",this.dL,this);this.o.subscribe("handlerMessage",this.eL,this);kBa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.ib.videoId;
g.dt()&&g.at("yt-remote-session-video-id",d)},this)},i8=function(a){k7("conn",a)},YBa=function(a,b){return new e7(h7(a.Y,"/bc"),b)},j8=function(a,b){a.S("proxyStateChange",b)},ZBa=function(a){a.C=g.Lo((0,g.x)(function(){i8("Connecting timeout");
this.Kk(1)},a),2E4)},k8=function(a){g.No(a.C);
a.C=NaN},l8=function(a){g.No(a.N);
a.N=NaN},$Ba=function(a){m8(a);
a.M=g.Lo((0,g.x)(function(){n8(this,"getNowPlaying")},a),2E4)},m8=function(a){g.No(a.M);
a.M=NaN},bCa=function(a,b){b&&(k8(a),l8(a));
b==(f7(a.o)&&isNaN(a.C))?b&&(j8(a,1),n8(a,"getSubtitlesTrack")):b?(a.vz()&&a.ib.reset(),j8(a,1),n8(a,"getNowPlaying"),aCa(a)):a.Kk(1)},cCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Ob(b.params)?a.ib.o=null:a.ib.o=b.params,a.S("remotePlayerChange"))},dCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;Y7(a.ib,c,d);a.S("remoteQueueChange")},fCa=function(a,b){b.params=b.params||{};
dCa(a,b);eCa(a,b);a.S("autoplayDismissed")},eCa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
W7(a.ib,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ib.playerState&&(c=-1E3);a.ib.playerState=c;c=Number(b.params.loadedTime);a.ib.M=isNaN(c)?0:c;c=Number(b.params.duration);a.ib.I=isNaN(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.ib.playerState?$Ba(a):m8(a);a.S("remotePlayerChange")},gCa=function(a,b){if(-1E3!=
a.ib.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.playerState=c;c=parseInt(b.params.currentTime,10);W7(a.ib,isNaN(c)?0:c);a.S("remotePlayerChange")}},hCa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=parseInt(b.params.volume,10);a.ib.muted=c;a.S("remotePlayerChange")},iCa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},jCa=function(a,b){var c="true"==b.params.hasNext;
a.ib.vg="true"==b.params.hasPrevious;a.ib.hasNext=c;a.S("previousNextChange")},aCa=function(a){g.No(a.I);
a.I=g.Lo((0,g.x)(a.Kk,a,1),864E5)},n8=function(a,b,c){c?i8("Sending: action="+b+", params="+g.Rk(c)):i8("Sending: action="+b);
a.o.sendMessage(b,c)},o8=function(a){o7.call(this,"ScreenServiceProxy");
this.Md=a;this.o=[];this.o.push(this.Md.$_s("screenChange",(0,g.x)(this.IP,this)));this.o.push(this.Md.$_s("onlineScreenChange",(0,g.x)(this.sM,this)))},oCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.K("MDX_CONFIG")||b;gAa();r6();p8||(p8=new g7(b?b.loungeApiHost:void 0),oAa()&&(p8.o="/api/loungedev"));q8||(q8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ha("yt.mdx.remote.deferredProxies_",q8,void 0));kCa();var c=r8();if(!c){var d=new x7(p8);g.Ha("yt.mdx.remote.screenService_",d,void 0);c=r8();var e=!1,f=void 0,h=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,h=b.theme,l=!!b.disableDial);PBa(a,d,function(m){m?s8()&&S7(s8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){f6("yt-remote-receiver-availability-change")})},e,f,h,l)}b&&!g.Ja("yt.mdx.remote.initialized_")&&(g.Ha("yt.mdx.remote.initialized_",!0,void 0),t8("Initializing: "+g.Rk(b)),u8.push(g.So("yt-remote-cast2-availability-change",function(){f6("yt-remote-receiver-availability-change")})),u8.push(g.So("yt-remote-cast2-receiver-selected",function(){v8(null);
f6("yt-remote-auto-connect","cast-selector-receiver")})),u8.push(g.So("yt-remote-cast2-receiver-resumed",function(){f6("yt-remote-receiver-resumed","cast-selector-receiver")})),u8.push(g.So("yt-remote-cast2-session-change",lCa)),u8.push(g.So("yt-remote-connection-change",function(m){m?S7(s8(),"YouTube TV"):w8()||(S7(null,null),SBa())})),a=x8(),b.isAuto&&(a.id+="#dial"),g.Bo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(h=b.theme)&&(a.theme=h),t8(" -- with channel params: "+
g.Rk(a)),mCa(a),c.start(),s8()||nCa())},qCa=function(){var a=pCa();
P7()&&g.bt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},pCa=function(){var a=r8().Md.$_gos();
var b=y8();b&&z8()&&(m6(a,b)||a.push(b));return fAa(a)},A8=function(){var a=rCa();
!a&&P7()&&RBa()&&(a={key:"cast-selector-receiver",name:RBa()});return a},rCa=function(){var a=pCa(),b=y8();
b||(b=w8());return g.cb(a,function(c){return b&&i6(b,c.key)?!0:!1})},y8=function(){var a=s8();
if(!a)return null;var b=r8().Me();return n6(b,a)},lCa=function(a){t8("remote.onCastSessionChange_: "+j6(a));
if(a){var b=y8();b&&b.id==a.id?S7(b.id,"YouTube TV"):(b&&B8(),C8(a,1))}else z8()&&B8()},B8=function(){Q7()?N7().stopSession():L7("stopSession called before API ready.");
var a=z8();a&&(a.disconnect(1),D8(null))},E8=function(){var a=z8();
return!!a&&3!=a.getProxyState()},t8=function(a){k7("remote",a)},r8=function(){if(!F8){var a=g.Ja("yt.mdx.remote.screenService_");
F8=a?new o8(a):null}return F8},s8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},sCa=function(a){g.Ha("yt.mdx.remote.currentScreenId_",a,void 0)},tCa=function(){return g.Ja("yt.mdx.remote.connectData_")},v8=function(a){g.Ha("yt.mdx.remote.connectData_",a,void 0)},z8=function(){return g.Ja("yt.mdx.remote.connection_")},D8=function(a){var b=z8();
v8(null);a||sCa("");g.Ha("yt.mdx.remote.connection_",a,void 0);q8&&((0,g.y)(q8,function(c){c(a)}),q8.length=0);
b&&!a?f6("yt-remote-connection-change",!1):!b&&a&&f6("yt-remote-connection-change",!0)},w8=function(){var a=g.dt();
if(!a)return null;var b=r8();if(!b)return null;b=b.Me();return n6(b,a)},C8=function(a,b){s8();
y8()&&y8();if(G8)H8=a;else{sCa(a.id);var c=new h8(p8,a,x8());c.connect(b,tCa());c.subscribe("beforeDisconnect",function(d){f6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){z8()&&(z8(),D8(null))});
D8(c)}},nCa=function(){var a=w8();
a?(t8("Resume connection to: "+j6(a)),C8(a,0)):(s6(),SBa(),t8("Skipping connecting because no session screen found."))},kCa=function(){var a=x8();
if(g.Ob(a)){a=q6();var b=g.bt("yt-remote-session-name")||"",c=g.bt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ha("yt.mdx.remote.channelParams_",a,void 0)}},x8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},mCa=function(a){a?(g.at("yt-remote-session-app",a.app),g.at("yt-remote-session-name",a.name)):(g.ct("yt-remote-session-app"),g.ct("yt-remote-session-name"));
g.Ha("yt.mdx.remote.channelParams_",a,void 0)},I8=function(a,b,c){g.A.call(this);
var d=this;this.module=a;this.H=b;this.ab=c;this.events=new g.es(this);this.M=this.events.L(this.H,"onVolumeChange",this.bC);this.B=!1;this.suggestion=null;this.C=new g.cG(64);this.o=new g.G(this.ID,500,this);this.u=new g.G(this.JD,1E3,this);this.G=new w6(this.oP,0,this);this.A={};this.I=new g.G(this.mE,1E3,this);this.F=new x6(this.seekTo,1E3,this);this.N=g.Ka;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.TL);this.events.L(b,"captionschanged",this.ZK);this.events.L(b,"captionssettingschanged",
this.LD);this.events.L(b,"videoplayerreset",this.lr);this.events.L(b,"mdxautoplaycancel",function(){d.ab.My()});
a=this.ab;a.ha();a.subscribe("proxyStateChange",this.tC,this);a.subscribe("remotePlayerChange",this.In,this);a.subscribe("remoteQueueChange",this.lr,this);a.subscribe("previousNextChange",this.pC,this);a.subscribe("nowAutoplaying",this.lC,this);a.subscribe("autoplayDismissed",this.LB,this);g.C(this,this.o);g.C(this,this.u);g.C(this,this.G);g.C(this,this.I);g.C(this,this.F);this.LD();this.lr();this.In()},uCa=function(a){a.Xb(0);
a.o.stop();a.Pc(new g.cG(64))},K8=function(a,b){if(J8(a)&&!a.B){var c=null;
b&&(c={style:a.H.getSubtitlesUserSettings()},g.Ub(c,b));a.ab.zE(a.H.getVideoData(1).videoId,c);a.A=b8(a.ab).o}},L8=function(a,b){var c=a.H.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.H.getVideoData(1);a.ab.playVideo(c.videoId,b,d,e,c.playerParams,c.lf,Tza(c));a.Pc(new g.cG(1))},vCa=function(a,b){if(b){var c=a.H.getOption("captions","tracklist",{Vz:1});
c&&c.length?(a.H.setOption("captions","track",b),a.B=!1):(a.H.loadModule("captions"),a.B=!0)}else a.H.setOption("captions","track",{})},J8=function(a){return b8(a.ab).videoId===a.H.getVideoData(1).videoId},M8=function(){g.T.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",V:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],V:"Learn more"},{D:"button",W:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],V:"OK"}]}]}]});this.o=new g.hO(this,250);this.learnMoreButton=
this.ca("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ca("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.o);this.L(this.learnMoreButton,"click",this.u);this.L(this.okButton,"click",this.A)},N8=function(){g.T.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",J:"ytp-mdx-popup-title",V:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",V:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],V:"Cancel"},{D:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],
V:"Confirm"}]}]}]});this.o=new g.hO(this,250);this.cancelButton=this.ca("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ca("ytp-mdx-privacy-popup-confirm");g.C(this,this.o);this.L(this.cancelButton,"click",this.u);this.L(this.confirmButton,"click",this.A)},O8=function(a){g.T.call(this,{D:"div",
J:"ytp-remote",K:[{D:"div",J:"ytp-remote-display-status",K:[{D:"div",J:"ytp-remote-display-status-icon",K:[g.kM()]},{D:"div",J:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.api=a;this.o=new g.hO(this,250);g.C(this,this.o);this.L(a,"presentingplayerstatechange",this.u);wCa(this,g.iM(a))},wCa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.S(b,128)?g.LL("Error on $RECEIVER_NAME",c):b.sb()||g.S(b,4)?g.LL("Playing on $RECEIVER_NAME",c):g.LL("Connected to $RECEIVER_NAME",c);a.la("statustext",c);a.o.show()}else a.o.hide()},P8=function(a,b){g.CR.call(this,"Play on",0,a,b);
this.H=a;this.Si={};this.L(a,"onMdxReceiversChange",this.B);this.L(a,"presentingplayerstatechange",this.B);this.B()},Q8=function(a){g.NN.call(this,a);
this.Qf={key:l6(),name:"This computer"};this.He=null;this.subscriptions=[];this.Jv=this.ab=null;this.Si=[this.Qf];this.fi=this.Qf;this.Sb=new g.cG(64);this.nA=0;this.ld=-1;this.pl=null;this.Jn=this.wq=!1;this.gk=this.Gl=null;if(!g.Ay(this.player.O())){a=this.player;var b=g.$M(a);b&&(b=b.xj())&&(b=new P8(a,b),g.C(this,b));b=new O8(a);g.C(this,b);g.zN(a,b.element,4);this.Gl=new N8;g.C(this,this.Gl);g.zN(a,this.Gl.element,4);g.P(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.pl=new M8,g.C(this,this.pl),g.zN(a,this.pl.element,4));this.Jn=!!w8();this.wq=!!g.bt("yt-remote-manual-pairing-warning-shown")}},R8=function(a){a.gk&&(a.player.removeEventListener("presentingplayerstatechange",a.gk),a.gk=null)},xCa=function(a,b,c){a.Sb=c;
a.player.S("presentingplayerstatechange",new g.lG(c,b))},yCa=function(a,b,c){var d=!1;
1===b?d=!a.Jn:2===b&&(d=!a.wq);d&&g.nG(c,8)&&(a.player.pauseVideo(),R8(a))},S8=function(a,b){if(b.key!==a.fi.key)if(b.key===a.Qf.key)B8();
else{if(a.pl&&!a.wq&&b!==a.Qf&&"cast-selector-receiver"!==b.key&&g.Jy(a.player.O()))zCa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.K("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.K("SESSION_INDEX")&&!g.K("LOGGED_IN")))||a.Jn||!a.Gl);(c?0:g.Jy(a.player.O())||g.Ny(a.player.O()))&&ACa(a)}a.fi=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.getLength();l++)h[l]=f.Aa(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.lf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Tza(c))&&(d.locationInfo=c);c=d}t8("Connecting to: "+g.Rk(b));"cast-selector-receiver"==b.key?(v8(c||null),c=
c||null,Q7()?N7().setLaunchParams(c):L7("setLaunchParams called before ready.")):!c&&E8()&&s8()==b.key?f6("yt-remote-connection-change",!0):(B8(),v8(c||null),c=r8().Me(),(c=n6(c,b.key))&&C8(c,1))}},ACa=function(a){g.iM(a.player).sb()?a.player.pauseVideo():(a.gk=function(b){yCa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.gk));
a.Gl&&a.Gl.Yb();z8()||(G8=!0)},zCa=function(a){g.iM(a.player).sb()?a.player.pauseVideo():(a.gk=function(b){yCa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.gk));
a.pl&&a.pl.Yb();z8()||(G8=!0)},EAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},K6={"'":"\\'"},BCa={},bAa={pQ:"atp",hT:"ska",RS:"que",gS:"mus",gT:"sus",oR:"dsp",ZS:"seq"},t6,p6="",tAa=pAa("loadCastFramework")||pAa("loadCastApplicationFramework"),OBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(w6,g.A);g.k=w6.prototype;g.k.MG=function(a){this.B=arguments;this.o=!1;this.Ka?this.A=(0,g.E)()+this.Nd:this.Ka=g.cg(this.C,this.Nd)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null);this.A=null;this.o=!1;this.B=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.k.X=function(){this.stop();w6.tc.X.call(this)};
g.k.NG=function(){this.A?(this.Ka=g.cg(this.C,this.A-(0,g.E)()),this.A=null):(this.Ka=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.t(x6,g.A);g.k=x6.prototype;g.k.BA=function(a){this.A=arguments;this.Ka||this.u?this.o=!0:y6(this)};
g.k.stop=function(){this.Ka&&(g.v.clearTimeout(this.Ka),this.Ka=null,this.o=!1,this.A=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.o||this.Ka||(this.o=!1,y6(this))};
g.k.X=function(){g.A.prototype.X.call(this);this.stop()};A6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
A6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};B6.prototype.o=null;B6.prototype.getOptions=function(){var a;(a=this.o)||(a={},xAa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var T8;g.Ua(wAa,B6);T8=new wAa;g.k=C6.prototype;g.k.Aj=null;g.k.eg=!1;g.k.Wl=null;g.k.ax=null;g.k.Kl=null;g.k.Pl=null;g.k.Zh=null;g.k.Ti=null;g.k.hk=null;g.k.fd=null;g.k.so=0;g.k.kg=null;g.k.qs=null;g.k.oi=null;g.k.Pm=-1;g.k.zD=!0;g.k.hj=!1;g.k.fu=0;g.k.yr=null;var CAa={},F6={};g.k=C6.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.vO=function(a){a=a.target;var b=this.yr;b&&3==T6(a)?b.BA():this.wE(a)};
g.k.wE=function(a){try{if(a==this.fd)a:{var b=T6(this.fd),c=this.fd.F,d=this.fd.getStatus();if(g.pe&&!g.Ud(10)||g.re&&!g.Td("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Gh&&!V6(this.fd))break a;this.hj||4!=b||7==c||(8==c||0>=d?this.o.Vf(3):this.o.Vf(2));M6(this);var e=this.fd.getStatus();this.Pm=e;var f=V6(this.fd);(this.eg=200==e)?(4==b&&I6(this),this.F?(DAa(this,b,f),g.Gh&&this.eg&&3==b&&(this.B.ma(this.u,"tick",this.pO),this.u.start())):H6(this,f),this.eg&&!this.hj&&(4==b?this.o.Tp(this):(this.eg=
!1,E6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.oi=3,G6(13)):(this.oi=0,G6(14)),I6(this),J6(this))}}catch(h){this.fd&&V6(this.fd)}finally{}};
g.k.pO=function(){var a=T6(this.fd),b=V6(this.fd);this.so<b.length&&(M6(this),DAa(this,a,b),this.eg&&4!=a&&E6(this))};
g.k.KN=function(a){L6((0,g.x)(this.JN,this,a),0)};
g.k.JN=function(a){this.hj||(M6(this),H6(this,a),E6(this))};
g.k.DC=function(a){L6((0,g.x)(this.IN,this,a),0)};
g.k.IN=function(a){this.hj||(I6(this),this.eg=a,this.o.Tp(this),this.o.Vf(4))};
g.k.cancel=function(){this.hj=!0;I6(this)};
g.k.SN=function(){this.Wl=null;var a=(0,g.E)();0<=a-this.ax?(2!=this.Pl&&this.o.Vf(3),I6(this),this.oi=2,G6(18),J6(this)):GAa(this,this.ax-a)};
g.k.getLastError=function(){return this.oi};g.k=JAa.prototype;g.k.du=null;g.k.ye=null;g.k.zr=!1;g.k.Fz=null;g.k.zp=null;g.k.Gu=null;g.k.eu=null;g.k.jf=null;g.k.qh=-1;g.k.Om=null;g.k.jm=null;g.k.connect=function(a){this.eu=a;a=O6(this.o,null,this.eu);G6(3);this.Fz=(0,g.E)();var b=this.o.I;null!=b?(this.Om=b[0],(this.jm=b[1])?(this.jf=1,KAa(this)):(this.jf=2,Q6(this))):(c6(a,"MODE","init"),this.ye=new C6(this,void 0,void 0,void 0),this.ye.Aj=this.du,D6(this.ye,a,!1,null,!0),this.jf=0)};
g.k.KF=function(a){if(a)this.jf=2,Q6(this);else{G6(4);var b=this.o;b.ug=b.ci.qh;b7(b,9)}a&&this.Vf(2)};
g.k.wt=function(a){return this.o.wt(a)};
g.k.abort=function(){this.ye&&(this.ye.cancel(),this.ye=null);this.qh=-1};
g.k.Ez=function(){return!1};
g.k.uC=function(a,b){this.qh=a.Pm;if(0==this.jf)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.ug=this.qh;b7(c,2);return}this.Om=c[0];this.jm=c[1]}else c=this.o,c.ug=this.qh,b7(c,2);else if(2==this.jf)if(this.zr)G6(7),this.Gu=(0,g.E)();else if("11111"==b){if(G6(6),this.zr=!0,this.zp=(0,g.E)(),c=this.zp-this.Fz,!g.pe||g.Ud(10)||500>c)this.qh=200,this.ye.cancel(),G6(12),P6(this.o,this,!0)}else G6(8),this.zp=this.Gu=(0,g.E)(),this.zr=!1};
g.k.Tp=function(){this.qh=this.ye.Pm;if(this.ye.eg)0==this.jf?this.jm?(this.jf=1,KAa(this)):(this.jf=2,Q6(this)):2==this.jf&&((!g.pe||g.Ud(10)?!this.zr:200>this.Gu-this.zp)?(G6(11),P6(this.o,this,!1)):(G6(12),P6(this.o,this,!0)));else{0==this.jf?G6(9):2==this.jf&&G6(10);var a=this.o;this.ye.getLastError();a.ug=this.qh;b7(a,2)}};
g.k.bo=function(){return this.o.bo()};
g.k.isActive=function(){return this.o.isActive()};
g.k.Vf=function(a){this.o.Vf(a)};g.Ua(R6,g.rf);var PAa=/^https?$/i,CCa=["POST","PUT"];g.k=R6.prototype;
g.k.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.fa=b;this.Y=!1;this.A=!0;this.o=this.T?yAa(this.T):yAa(T8);this.U=this.T?this.T.getOptions():T8.getOptions();this.o.onreadystatechange=(0,g.x)(this.qC,this);try{e6(U6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){e6(U6(this,"Error opening Xhr: "+f.message));OAa(this,f);return}a=
c||"";var e=this.headers.clone();d&&Yza(d,function(f,h){e.set(h,f)});
d=g.cb(e.gf(),MAa);c=g.v.FormData&&a instanceof g.v.FormData;!g.fb(CCa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.o.setRequestHeader(h,f)},this);
this.ga&&(this.o.responseType=this.ga);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{RAa(this),0<this.G&&(this.R=LAa(this.o),e6(U6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Gz,this)):this.N=g.cg(this.Gz,this.G,this)),e6(U6(this,"Sending request")),this.I=!0,this.o.send(a),this.I=!1}catch(f){e6(U6(this,"Send error: "+f.message)),OAa(this,f)}};
g.k.Gz=function(){"undefined"!=typeof g.E1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,U6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.o&&this.A&&(U6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),S6(this))};
g.k.X=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),S6(this,!0));R6.tc.X.call(this)};
g.k.qC=function(){this.ha()||(this.aa||this.I||this.C?QAa(this):this.RM())};
g.k.RM=function(){QAa(this)};
g.k.isActive=function(){return!!this.o};
g.k.getStatus=function(){try{return 2<T6(this)?this.o.status:-1}catch(a){return-1}};
g.k.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.k=W6.prototype;g.k.Dm=null;g.k.le=null;g.k.Dc=null;g.k.cu=null;g.k.Cp=null;g.k.hy=null;g.k.Sp=null;g.k.xn=0;g.k.vK=0;g.k.Kd=null;g.k.hi=null;g.k.Zg=null;g.k.mj=null;g.k.ci=null;g.k.ks=null;g.k.ll=-1;g.k.mA=-1;g.k.ug=-1;g.k.Pk=0;g.k.Bk=0;g.k.ij=8;var c7=new g.rf;g.Ua(TAa,g.Qe);g.Ua(UAa,g.Qe);g.Ua(VAa,g.Qe);g.k=W6.prototype;g.k.connect=function(a,b,c,d,e){G6(0);this.cu=b;this.Dm=c||{};d&&void 0!==e&&(this.Dm.OSID=d,this.Dm.OAID=e);this.F?(L6((0,g.x)(this.zy,this,a),100),ZAa(this)):this.zy(a)};
g.k.zy=function(a){this.ci=new JAa(this);this.ci.du=null;this.ci.u=this.C;this.ci.connect(a)};
g.k.Ez=function(){return 0==this.o};
g.k.CC=function(a){this.hi=null;bBa(this,a)};
g.k.BC=function(){this.Zg=null;this.Dc=new C6(this,this.A,"rpc",this.G);this.Dc.Aj=null;this.Dc.fu=0;var a=this.hy.clone();a6(a,"RID","rpc");a6(a,"SID",this.A);a6(a,"CI",this.ks?"0":"1");a6(a,"AID",this.ll);X6(this,a);if(!g.pe||g.Ud(10))a6(a,"TYPE","xmlhttp"),D6(this.Dc,a,!0,this.Sp,!1);else{a6(a,"TYPE","html");var b=this.Dc,c=!!this.Sp;b.Pl=3;b.Zh=b6(a.clone());FAa(b,c)}};
g.k.uC=function(a,b){if(0!=this.o&&(this.Dc==a||this.le==a))if(this.ug=a.Pm,this.le==a&&3==this.o)if(7<this.ij){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Zg){if(this.Dc)if(this.Dc.Kl+3E3<this.le.Kl)Z6(this),this.Dc.cancel(),this.Dc=null;else break a;a7(this);G6(19)}}else this.mA=c[1],0<this.mA-this.ll&&37500>c[2]&&this.ks&&0==this.Bk&&!this.mj&&(this.mj=L6((0,g.x)(this.VK,this),6E3));else b7(this,11)}else b!=BCa.NQ.o&&b7(this,11);else if(this.Dc==
a&&Z6(this),!g.kc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.ll=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.Sp=e[2],e=e[3],null!=e?this.ij=e:this.ij=6,this.o=3,this.Kd&&this.Kd.ty(),this.hy=O6(this,this.bo()?this.Sp:null,this.cu),cBa(this)):"stop"==e[0]&&b7(this,7):3==this.o&&("stop"==e[0]?b7(this,7):"noop"!=e[0]&&this.Kd&&this.Kd.sy(e),this.Bk=0)}}};
g.k.VK=function(){null!=this.mj&&(this.mj=null,this.Dc.cancel(),this.Dc=null,a7(this),G6(20))};
g.k.Tp=function(a){if(this.Dc==a){Z6(this);this.Dc=null;var b=2}else if(this.le==a)this.le=null,b=1;else return;this.ug=a.Pm;if(0!=this.o)if(a.eg)1==b?(b=(0,g.E)()-a.Kl,c7.dispatchEvent(new UAa(c7,a.hk?a.hk.length:0,b,this.Pk)),Y6(this),this.B.length=0):cBa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.ug)){if(d=1==b)this.le||this.hi||1==this.o||2<=this.Pk?d=!1:(this.hi=L6((0,g.x)(this.CC,this,a),dBa(this,this.Pk)),this.Pk++,d=!0);d=!(d||2==b&&a7(this))}if(d)switch(c){case 1:b7(this,
5);break;case 4:b7(this,10);break;case 3:b7(this,6);break;case 7:b7(this,12);break;default:b7(this,2)}}};
g.k.lG=function(a){if(!g.fb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.k.eP=function(a){a?G6(2):(G6(1),eBa(this,8))};
g.k.wt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new R6;a.Z=!1;return a};
g.k.isActive=function(){return!!this.Kd&&this.Kd.isActive(this)};
g.k.Vf=function(a){c7.dispatchEvent(new VAa(c7,a))};
g.k.bo=function(){return!(!g.pe||g.Ud(10))};
g.k=fBa.prototype;g.k.ty=function(){};
g.k.sy=function(){};
g.k.ry=function(){};
g.k.gt=function(){};
g.k.cz=function(){return{}};
g.k.isActive=function(){return!0};g.k=gBa.prototype;g.k.isEmpty=function(){return g.gb(this.o)&&g.gb(this.u)};
g.k.clear=function(){this.o=[];this.u=[]};
g.k.contains=function(a){return g.fb(this.o,a)||g.fb(this.u,a)};
g.k.remove=function(a){var b=this.o;var c=(0,g.xua)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.u,a)};
g.k.Wd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(d7,g.A);g.k=d7.prototype;g.k.DN=function(){this.Nd=Math.min(3E5,2*this.Nd);this.A();this.u&&this.start()};
g.k.start=function(){var a=this.Nd+15E3*Math.random();this.o.jb(a);this.u=(0,g.E)()+a};
g.k.stop=function(){this.o.stop();this.u=0};
g.k.isActive=function(){return this.o.isActive()};
g.k.reset=function(){this.o.stop();this.Nd=5E3};g.Ua(e7,fBa);g.k=e7.prototype;g.k.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.k.Ki=function(a){return this.A.Bj(a)};
g.k.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.k.dispose=function(){this.Sc||(this.Sc=!0,g.Oe(this.A),jBa(this),g.Oe(this.u),this.u=null)};
g.k.ha=function(){return this.Sc};
g.k.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.N+"/test";b=this.N+"/bind";var d=new W6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Kd=null);d.Kd=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.ll):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Ub(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):f7(this)&&$Aa(this.o,c)};
g.k.ty=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)$Aa(this.o,a[b])}this.S("handlerOpened")};
g.k.ry=function(a){var b=2==a&&401==this.o.ug;4==a||b||this.u.start();this.S("handlerError",a)};
g.k.gt=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.k.cz=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.I&&(a.ui=""+this.I);this.C&&g.Ub(a,this.C);return a};
g.k.sy=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),YAa(this.o)):this.S("handlerMessage",new hBa(a[0],a[1]))};
g.k.JO=function(){this.u.isActive();var a=this.o,b=0;a.Dc&&b++;a.le&&b++;0==b&&this.connect(this.C,this.B)};g7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
g7.prototype.C=function(a){a(Error("request timed out"))};var rBa=(0,g.E)(),j7=null,m7=Array(50),l7=-1,n7=!1;g.Ua(o7,g.N);o7.prototype.Me=function(){return this.screens};
o7.prototype.contains=function(a){return!!m6(this.screens,a)};
o7.prototype.get=function(a){return a?n6(this.screens,a):null};
o7.prototype.info=function(a){k7(this.F,a)};g.t(p7,g.N);g.k=p7.prototype;g.k.start=function(){!this.o&&isNaN(this.Ka)&&this.AE()};
g.k.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ka)||(g.No(this.Ka),this.Ka=NaN)};
g.k.X=function(){this.stop();g.N.prototype.X.call(this)};
g.k.AE=function(){this.Ka=NaN;this.o=g.vq(h7(this.F,"/pairing/get_screen"),{method:"POST",Cb:{pairing_code:this.C},timeout:5E3,onSuccess:(0,g.x)(this.GP,this),onError:(0,g.x)(this.FP,this),Se:(0,g.x)(this.HP,this)})};
g.k.GP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.A;c.name=this.B;this.S("pairingComplete",new h6(c))};
g.k.FP=function(a){this.o=null;a.status&&404==a.status?this.u>=DCa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=DCa[this.u],this.Ka=g.Lo((0,g.x)(this.AE,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.HP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var DCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(r7,o7);g.k=r7.prototype;g.k.start=function(){q7(this)&&this.S("screenChange");!g.bt("yt-remote-lounge-token-expiration")&&vBa(this);g.No(this.o);this.o=g.Lo((0,g.x)(this.start,this),1E4)};
g.k.add=function(a,b){q7(this);sBa(this,a);s7(this,!1);this.S("screenChange");b(a);a.token||vBa(this)};
g.k.remove=function(a,b){var c=q7(this);uBa(this,a)&&(s7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.gs=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,s7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.X=function(){g.No(this.o);r7.tc.X.call(this)};
g.k.YG=function(a){q7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}s7(this,!b);b&&k7(this.F,"Missed "+b+" lounge tokens.")};
g.k.XG=function(a){k7(this.F,"Requesting lounge tokens failed: "+a)};g.t(u7,g.N);g.k=u7.prototype;g.k.start=function(){var a=parseInt(g.bt("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.E)()-144E5<a?0:a)?w7(this):(this.B=(0,g.E)()+3E5,g.at("yt-remote-fast-check-period",this.B),this.Wv())};
g.k.isEmpty=function(){return g.Ob(this.o)};
g.k.update=function(){t7("Updating availability on schedule.");var a=this.F(),b=g.Bb(this.o,function(c,d){return c&&!!n6(a,d)},this);
v7(this,b)};
g.k.X=function(){g.No(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.N.prototype.X.call(this)};
g.k.Wv=function(){g.No(this.A);this.A=NaN;this.u&&this.u.abort();var a=yBa(this);if(d6(a)){var b=h7(this.C,"/pairing/get_screen_availability");this.u=i7(this.C,b,{lounge_token:g.Hb(a).join(",")},(0,g.x)(this.nN,this,a),(0,g.x)(this.mN,this))}else v7(this,{}),w7(this)};
g.k.nN=function(a,b){this.u=null;var c=g.Hb(yBa(this));if(g.xb(c,g.Hb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.pc("Changing Screen set during request."),this.Wv()};
g.k.mN=function(a){this.pc("Screen availability failed: "+a);this.u=null;w7(this)};
g.k.pc=function(a){k7("OnlineScreenService",a)};g.Ua(x7,o7);g.k=x7.prototype;g.k.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.k.gs=function(a,b,c,d){this.u.contains(a)?this.u.gs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,k7(this.F,a),d(Error(a)))};
g.k.Me=function(a){return a?this.screens:g.nb(this.screens,(0,g.Ce)(this.A,function(b){return!this.contains(b)},this))};
g.k.BE=function(){return(0,g.Ce)(this.Me(!0),function(a){return!!this.o.o[a.id]},this)};
g.k.CE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(h){g.Oe(f);d(y7(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Oe(f);e(h)});
f.start();return(0,g.x)(f.stop,f)};
g.k.JP=function(a,b,c,d){g.vq(h7(this.C,"/pairing/get_screen"),{method:"POST",Cb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var h=new h6(f.screen||{});if(!h.name||CBa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);CBa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(y7(this,h))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Se:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.k.X=function(){g.Oe(this.u);g.Oe(this.o);x7.tc.X.call(this)};
g.k.fH=function(){DBa(this);this.S("screenChange");this.o.update()};
x7.prototype.dispose=x7.prototype.dispose;g.Ua(A7,g.N);g.k=A7.prototype;g.k.getScreen=function(){return this.I};
g.k.kr=function(a){this.I=a;this.S("sessionScreen",this.I)};
g.k.Re=function(a){this.ha()||(a&&B7(this,""+a),this.I=null,this.S("sessionScreen",null))};
g.k.info=function(a){k7(this.U,a)};
g.k.EE=function(){return null};
g.k.iw=function(a){var b=this.o;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){B7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.X=function(){this.iw("");A7.tc.X.call(this)};g.t(C7,A7);g.k=C7.prototype;g.k.hw=function(a){if(this.u){if(this.u==a)return;B7(this,"Overriding cast sesison with new session object");this.u.removeUpdateListener(this.C);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.u=a;this.u.addUpdateListener(this.C);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);FBa(this)};
g.k.nl=function(a){this.info("launchWithParams no-op for Cast: "+g.Rk(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.x)(function(){this.Re()},this),(0,g.x)(function(){this.Re(Error("Failed to stop receiver app."))},this)):this.Re(Error("Stopping cast device witout session."))};
g.k.iw=function(){};
g.k.X=function(){this.info("disposeInternal");g.No(this.A);this.A=0;this.u&&(this.u.removeUpdateListener(this.C),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.u=null;A7.prototype.X.call(this)};
g.k.bO=function(a,b){if(!this.ha())if(b){var c=z6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Rk(c));switch(d){case "mdxSessionStatus":EBa(this,c.screenId);break;default:B7(this,"Unknown youtube message: "+d)}}else B7(this,"Unable to parse message.")}else B7(this,"No data in message.")};
g.k.xz=function(a,b,c,d){BBa(this.M,this.o.label,a,this.o.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(B7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Lo((0,g.x)(this.xz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.EE=function(){return this.u};
g.k.KP=function(a){this.ha()||a||(B7(this,"Cast session died."),this.Re())};g.t(D7,A7);g.k=D7.prototype;g.k.hw=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.k.nl=function(a){this.B=a;this.F()};
g.k.stop=function(){this.u();this.u=g.Ka;g.No(this.C);this.A?this.A.stop((0,g.x)(this.Re,this,null),(0,g.x)(this.Re,this,"Failed to stop DIAL device.")):this.Re()};
g.k.X=function(){this.u();this.u=g.Ka;g.No(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;A7.prototype.X.call(this)};
g.k.NP=function(a){this.ha()||a||(B7(this,"DIAL session died."),this.u(),this.u=g.Ka,this.Re())};
g.k.pu=function(a){this.N=l6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,HBa(this));a(b);GBa(this)}else this.F=(0,g.x)(function(){g.No(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,HBa(this));a(c);GBa(this)},this),this.C=g.Lo((0,g.x)(function(){this.F()},this),100)};
g.k.vH=function(a,b,c){BBa(this.M,this.G.receiver.label,a,this.o.friendlyName,(0,g.x)(function(d){d&&d.token?(this.kr(d),b(new chrome.cast.DialLaunchResponse(!1))):this.pu(b,c)},this),(0,g.x)(function(d){B7(this,"Failed to get DIAL screen: "+d);
this.pu(b,c)},this))};g.t(E7,A7);E7.prototype.stop=function(){this.Re()};
E7.prototype.hw=function(){};
E7.prototype.nl=function(){g.No(this.u);this.u=NaN;var a=n6(this.M.Me(),this.o.label);a?this.kr(a):this.Re(Error("No such screen"))};
E7.prototype.X=function(){g.No(this.u);this.u=NaN;A7.prototype.X.call(this)};g.t(F7,g.N);g.k=F7.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.I||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.WM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.xC,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.qL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),oBa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.DE,this)),this.A=JBa(this),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(h){this.pc("Failed to set initial custom receivers: "+g.Rk(h))},this)),this.S("yt-remote-cast2-availability-change",H7(this)),b(!0))},this),(0,g.x)(function(h){this.pc("Failed to initialize API: "+g.Rk(h));
b(!1)},this))};
g.k.PO=function(a,b){G7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)G7("Unsetting old screen status: "+this.o.o.friendlyName),I7(this,null)}if(a&&b){if(!this.o){c=n6(this.u.Me(),a);if(!c){G7("setConnectedScreenStatus: Unknown screen.");return}var d=IBa(this,c);d||(G7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ka,(0,g.x)(function(e){this.pc("Failed to set initial custom receivers: "+g.Rk(e))},this)));
G7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);I7(this,new E7(this.u,d),!0)}this.o.iw(b)}else G7("setConnectedScreenStatus: no screen.")};
g.k.QO=function(a){this.ha()?this.pc("Setting connection data on disposed cast v2"):this.o?this.o.nl(a):this.pc("Setting connection data without a session")};
g.k.MP=function(){this.ha()?this.pc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),I7(this,null)):G7("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.xC,this),(0,g.x)(this.qN,this))};
g.k.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.DE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=lBa,b=g.Ja("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Oe(this.o);g.N.prototype.X.call(this)};
g.k.pc=function(a){k7("Controller",a)};
g.k.zC=function(a,b){this.o==a&&(b||I7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.SM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),G7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.o.label!=a.label)G7("onReceiverAction_: Stopping active receiver: "+this.o.o.friendlyName),this.o.stop();else{G7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:I7(this,
new E7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:I7(this,new D7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:I7(this,new C7(this.u,a));break;default:this.pc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.o.label==a.label?this.o.stop():this.pc("Stopping receiver w/o session: "+a.friendlyName)}else this.pc("onReceiverAction_ called without receiver.")};
g.k.qL=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.pc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.o:null;if(!c||c.label!=b.label)return this.pc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return G7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.pc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);I7(this,new D7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.vH,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.pu,b))};
g.k.xC=function(a){if(!this.ha()){G7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)G7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),I7(this,new C7(this.u,b),!0);else{this.pc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.o,d=n6(this.u.Me(),c.label);d&&i6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(G7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Oe(this.o),this.o=new C7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.zC,this,this.o)),this.o.nl(null));this.o.hw(a)}}};
g.k.LP=function(){return this.o?this.o.EE():null};
g.k.qN=function(a){this.ha()||(this.pc("Failed to estabilish a session: "+g.Rk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&I7(this,null))};
g.k.WM=function(a){G7("Receiver availability updated: "+a);if(!this.ha()){var b=H7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;H7(this)!=b&&this.S("yt-remote-cast2-availability-change",H7(this))}};
g.k.DE=function(){this.ha()||(this.A=JBa(this),G7("Updating custom receivers: "+g.Rk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ka,(0,g.x)(function(){this.pc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",H7(this)))};
F7.prototype.setLaunchParams=F7.prototype.QO;F7.prototype.setConnectedScreenStatus=F7.prototype.PO;F7.prototype.stopSession=F7.prototype.MP;F7.prototype.getCastSession=F7.prototype.LP;F7.prototype.requestSession=F7.prototype.requestSession;F7.prototype.init=F7.prototype.init;F7.prototype.dispose=F7.prototype.dispose;var O7=[];g.k=T7.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";U7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.vg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.I=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.k.sb=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.A?this.I+V7(this):this.I};
g.k.clone=function(){return new T7(Z7(this))};g.t(a8,g.N);g.k=a8.prototype;g.k.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,g8(this,"play")):f8(this,"play"),e8(this,1,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.play)};
g.k.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,g8(this,"pause")):f8(this,"pause"),e8(this,2,X7(b8(this))),this.S("remotePlayerChange")):c8(this,this.pause)};
g.k.seekTo=function(a){if(1==this.o){if(this.u){var b=b8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,g8(this,"seekTo",{newTime:a}))}else f8(this,"seekTo",{newTime:a});e8(this,3,a);this.S("remotePlayerChange")}else c8(this,g.Sa(this.seekTo,a))};
g.k.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,g8(this,"stopVideo")):f8(this,"stopVideo");var a=b8(this);a.index=-1;a.videoId="";U7(a);d8(this,a);this.S("remotePlayerChange")}else c8(this,this.stop)};
g.k.setVolume=function(a,b){if(1==this.o){var c=b8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){k7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.pc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){k7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.pc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);f8(this,"setVolume",e)}c.muted=b;c.volume=a;d8(this,c)}else c8(this,g.Sa(this.setVolume,a,b))};
g.k.zE=function(a,b){if(1==this.o){var c=b8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Rk(b.style),g.Ub(d,c.o));f8(this,"setSubtitlesTrack",d);d8(this,c)}else c8(this,g.Sa(this.zE,a,b))};
g.k.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();f8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=b8(this);d.audioTrackId=c;d8(this,d)}else c8(this,g.Sa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=b8(this);c=c||0;var m={videoId:a,currentIndex:c};Y7(l,a,c);void 0!==b&&(W7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Rk(h));f8(this,"setPlaylist",m);d||d8(this,l)};
g.k.ur=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"previous")}else c8(this,g.Sa(this.ur,a,b))};
g.k.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=b8(this);Y7(c,a,b);d8(this,c)}f8(this,"next")}else c8(this,g.Sa(this.nextVideo,a,b))};
g.k.My=function(){1==this.o?f8(this,"dismissAutoplay"):c8(this,this.My)};
g.k.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.N.prototype.dispose.call(this)};
g.k.X=function(){WBa(this);this.B=null;this.C.clear();$7(this,null);g.N.prototype.X.call(this)};
g.k.ex=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.gb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.k.PM=function(a,b){this.S(a,b)};
g.k.bL=function(a){if(!a)this.Bn(null),$7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=b8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)k7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,d8(this,b)}};
g.k.Bn=function(a){k7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.I);if(this.u=a)this.u.addUpdateListener(this.I),XBa(this),this.S("remotePlayerChange")};
g.k.aL=function(a){a?(XBa(this),this.S("remotePlayerChange")):this.Bn(null)};
g.k.Ew=function(){f8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.jL=function(){var a=TBa();a&&$7(this,a)};
g.k.pc=function(a){k7("CP",a)};g.t(h8,g.N);g.k=h8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=h||0;this.ib.state=3;W7(this.ib,m);this.B="UNSUPPORTED";i8("Connecting with setPlaylist and params: "+g.Rk(l));this.o.connect({method:"setPlaylist",
params:g.Rk(l)},a,jAa())}else i8("Connecting without params"),this.o.connect({},a,jAa());ZBa(this)};
g.k.dispose=function(){this.ha()||(this.S("beforeDispose"),j8(this,3));g.N.prototype.dispose.call(this)};
g.k.X=function(){k8(this);m8(this);l8(this);g.No(this.G);this.G=NaN;g.No(this.I);this.I=NaN;this.A=null;g.ip(this.U);this.U.length=0;this.o.dispose();g.N.prototype.X.call(this);this.B=this.F=this.u=this.ib=this.o=null};
g.k.QG=function(){this.Kk(2)};
g.k.fL=function(){i8("Channel opened");this.R&&(this.R=!1,l8(this),this.N=g.Lo((0,g.x)(function(){i8("Timing out waiting for a screen.");this.Kk(1)},this),15E3));
nAa(iBa(this.o),this.T)};
g.k.cL=function(){i8("Channel closed");isNaN(this.C)?s6(!0):s6();this.dispose()};
g.k.dL=function(a){s6();isNaN(this.Km())?(i8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,i8("Channel error: "+a+" with reconnection in "+this.Km()+" ms"),j8(this,2))};
g.k.eL=function(a){a.params?i8("Received: action="+a.action+", params="+g.Rk(a.params)):i8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=z6(a.params.devices);this.u=(0,g.Lc)(a,function(c){return new g6(c)});
a=!!g.cb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
bCa(this,a);break;case "loungeScreenDisconnected":g.lb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
bCa(this,!1);break;case "remoteConnected":var b=new g6(z6(a.params.device));g.cb(this.u,function(c){return b?c.id==b.id:!1})||Uza(this.u,b);
break;case "remoteDisconnected":b=new g6(z6(a.params.device));g.lb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":dCa(this,a);break;case "nowPlaying":fCa(this,a);break;case "onStateChange":eCa(this,a);break;case "onAdStateChange":gCa(this,a);break;case "onVolumeChanged":hCa(this,a);break;case "onSubtitlesTrackChanged":cCa(this,a);break;case "nowAutoplaying":iCa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":jCa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:i8("Unrecognized action: "+a.action)}};
g.k.FO=function(){if(this.A){var a=this.A;this.A=null;this.ib.videoId!=a&&n8(this,"getNowPlaying")}};
g.k.GG=function(){var a=3;this.ha()||(a=0,isNaN(this.Km())?f7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Kk=function(a){i8("Disconnecting with "+a);k8(this);this.S("beforeDisconnect",a);1==a&&s6();jBa(this.o,a);this.dispose()};
g.k.EG=function(){var a=this.ib;this.A&&(a=this.ib.clone(),Y7(a,this.A,a.index));return Z7(a)};
g.k.RO=function(a){var b=new T7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.A=b.videoId,g.No(this.G),this.G=g.Lo((0,g.x)(this.FO,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.playerState==b.playerState&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&X7(this.ib)==X7(b)&&g.Rk(this.ib.o)==g.Rk(b.o)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.k.vz=function(){var a=this.o.F.id,b=g.cb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Km=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.E)():NaN};
g.k.tG=function(){return this.B||"UNSUPPORTED"};
g.k.uG=function(){return this.F||""};
g.k.EP=function(){if(!isNaN(this.Km())){var a=this.o.u;g.Dn(a.o);a.start()}};
g.k.NO=function(a,b){n8(this,a,b);aCa(this)};
h8.prototype.subscribe=h8.prototype.subscribe;h8.prototype.unsubscribeByKey=h8.prototype.Ki;h8.prototype.getProxyState=h8.prototype.GG;h8.prototype.disconnect=h8.prototype.Kk;h8.prototype.getPlayerContextData=h8.prototype.EG;h8.prototype.setPlayerContextData=h8.prototype.RO;h8.prototype.getOtherConnectedRemoteId=h8.prototype.vz;h8.prototype.getReconnectTimeout=h8.prototype.Km;h8.prototype.getAutoplayMode=h8.prototype.tG;h8.prototype.getAutoplayVideoId=h8.prototype.uG;h8.prototype.reconnect=h8.prototype.EP;
h8.prototype.sendMessage=h8.prototype.NO;g.t(o8,o7);g.k=o8.prototype;g.k.Me=function(a){return this.Md.$_gs(a)};
g.k.contains=function(a){return!!this.Md.$_c(a)};
g.k.get=function(a){return this.Md.$_g(a)};
g.k.start=function(){this.Md.$_st()};
g.k.add=function(a,b,c){this.Md.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Md.$_r(a,b,c)};
g.k.gs=function(a,b,c,d){this.Md.$_un(a,b,c,d)};
g.k.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.Md.$_ubk(this.o[a]);this.o.length=0;this.Md=null;o7.prototype.X.call(this)};
g.k.IP=function(){this.S("screenChange")};
g.k.sM=function(){this.S("onlineScreenChange")};
x7.prototype.$_st=x7.prototype.start;x7.prototype.$_gspc=x7.prototype.JP;x7.prototype.$_gsppc=x7.prototype.CE;x7.prototype.$_c=x7.prototype.contains;x7.prototype.$_g=x7.prototype.get;x7.prototype.$_a=x7.prototype.add;x7.prototype.$_un=x7.prototype.gs;x7.prototype.$_r=x7.prototype.remove;x7.prototype.$_gs=x7.prototype.Me;x7.prototype.$_gos=x7.prototype.BE;x7.prototype.$_s=x7.prototype.subscribe;x7.prototype.$_ubk=x7.prototype.Ki;var H8=null,G8=!1,p8=null,q8=null,F8=null,u8=[];g.t(I8,g.A);g.k=I8.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.o.stop();this.u.stop();this.G.stop();this.N();var a=this.ab;a.unsubscribe("proxyStateChange",this.tC,this);a.unsubscribe("remotePlayerChange",this.In,this);a.unsubscribe("remoteQueueChange",this.lr,this);a.unsubscribe("previousNextChange",this.pC,this);a.unsubscribe("nowAutoplaying",this.lC,this);a.unsubscribe("autoplayDismissed",this.LB,this);this.ab=this.module=null};
g.k.RA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.ab.o)if(J8(this)){if(!b8(this.ab).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":b8(this.ab).sb()?this.ab.pause():this.ab.play();break;case "control_play":this.ab.play();break;case "control_pause":this.ab.pause();break;case "control_seek":this.F.BA(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.H.getCurrentTime();L8(this,0===c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.ZK=function(a){this.G.MG(a)};
g.k.oP=function(a){this.RA("control_subtitles_set_track",g.Ob(a)?null:a)};
g.k.LD=function(){var a=this.H.getOption("captions","track");g.Ob(a)||K8(this,a)};
g.k.Xb=function(a){this.module.Xb(a,this.H.getVideoData().lengthSeconds)};
g.k.bC=function(a){if(J8(this)){this.ab.unsubscribe("remotePlayerChange",this.In,this);var b=Math.round(a.volume);a=!!a.muted;var c=b8(this.ab);if(b!==c.volume||a!==c.muted)this.ab.setVolume(b,a),this.I.start();this.ab.subscribe("remotePlayerChange",this.In,this)}};
g.k.TL=function(){g.Ob(this.A)||vCa(this,this.A);this.B=!1};
g.k.tC=function(a,b){this.u.stop();2===b&&this.JD()};
g.k.In=function(){if(J8(this)){this.o.stop();var a=b8(this.ab);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.ld=1;break;case 1082:case 1083:this.module.ld=0;break;default:this.module.ld=-1}switch(a.playerState){case 1081:case 1:this.Pc(new g.cG(8));this.ID();break;case 1085:case 3:this.Pc(new g.cG(9));break;case 1083:case 0:this.Pc(new g.cG(2));this.F.stop();this.Xb(this.H.getVideoData().lengthSeconds);break;case 1084:this.Pc(new g.cG(4));break;case 2:this.Pc(new g.cG(4));
this.Xb(X7(a));break;case -1:this.Pc(new g.cG(64));break;case -1E3:this.Pc(new g.cG(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=b8(this.ab).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,vCa(this,a));a=b8(this.ab);-1===a.volume||Math.round(this.H.getVolume())===a.volume&&this.H.isMuted()===a.muted||this.I.isActive()||this.mE()}else uCa(this)};
g.k.pC=function(){this.H.S("mdxpreviousnextchange")};
g.k.lr=function(){J8(this)||uCa(this)};
g.k.lC=function(a){isNaN(a)||this.H.S("mdxnowautoplaying",a)};
g.k.LB=function(){this.H.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){J8(this)&&this.ab.setAudioTrack(this.H.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===b8(this.ab).playerState?L8(this,a):b&&this.ab.seekTo(a)};
g.k.mE=function(){if(J8(this)){var a=b8(this.ab);this.events.ob(this.M);a.muted?this.H.mute():this.H.unMute();this.H.setVolume(a.volume);this.M=this.events.L(this.H,"onVolumeChange",this.bC)}};
g.k.ID=function(){this.o.stop();if(!this.ab.ha()){var a=b8(this.ab);a.sb()&&this.Pc(new g.cG(8));this.Xb(X7(a));this.o.start()}};
g.k.JD=function(){this.u.stop();this.o.stop();var a=this.ab.B.getReconnectTimeout();2==this.ab.o&&!isNaN(a)&&this.u.start()};
g.k.Pc=function(a){this.u.stop();var b=this.C;if(!g.hG(b,a)){var c=g.S(a,2);c!==g.S(this.C,2)&&g.TT(this.H.app,c);this.C=a;xCa(this.module,b,a)}};g.t(M8,g.T);M8.prototype.Yb=function(){this.o.show()};
M8.prototype.Sa=function(){this.o.hide()};
M8.prototype.u=function(){g.oO("https://support.google.com/youtube/answer/7640706")};
M8.prototype.A=function(){f6("mdx-manual-pairing-popup-ok");this.Sa()};g.t(N8,g.T);N8.prototype.Yb=function(){this.o.show()};
N8.prototype.Sa=function(){this.o.hide()};
N8.prototype.u=function(){f6("mdx-privacy-popup-cancel");this.Sa()};
N8.prototype.A=function(){f6("mdx-privacy-popup-confirm");this.Sa()};g.t(O8,g.T);O8.prototype.u=function(a){wCa(this,a.state)};g.t(P8,g.CR);P8.prototype.B=function(){var a=this.H.getOption("remote","receivers");a&&1<a.length&&!this.H.getOption("remote","quickCast")?(this.Si=g.zb(a,this.o,this),g.ER(this,(0,g.Lc)(a,this.o)),a=this.H.getOption("remote","currentReceiver"),this.Nb(this.o(a)),this.enable(!0)):this.enable(!1)};
P8.prototype.o=function(a){return a.key};
P8.prototype.Tf=function(a){return"cast-selector-receiver"===a?"Cast...":this.Si[a].name};
P8.prototype.yd=function(a){g.CR.prototype.yd.call(this,a);this.H.setOption("remote","currentReceiver",this.Si[a]);this.Ma.Sa()};g.t(Q8,g.NN);g.k=Q8.prototype;
g.k.create=function(){oCa(g.py(this.player.O()));this.subscriptions.push(g.So("yt-remote-before-disconnect",this.XK,this));this.subscriptions.push(g.So("yt-remote-connection-change",this.XM,this));this.subscriptions.push(g.So("yt-remote-receiver-availability-change",this.rC,this));this.subscriptions.push(g.So("yt-remote-auto-connect",this.VM,this));this.subscriptions.push(g.So("yt-remote-receiver-resumed",this.UM,this));this.subscriptions.push(g.So("mdx-privacy-popup-confirm",this.tO,this));this.subscriptions.push(g.So("mdx-privacy-popup-cancel",
this.sO,this));this.subscriptions.push(g.So("mdx-manual-pairing-popup-ok",this.NH,this));this.rC()};
g.k.load=function(){this.player.cancelPlayback();g.NN.prototype.load.call(this);this.He=new I8(this,this.player,this.ab);var a=(a=tCa())?a.currentTime:0;var b=E8()?new a8(z8(),void 0):null;0==a&&b&&(a=X7(b8(b)));0!==a&&this.Xb(a);xCa(this,this.Sb,this.Sb);g.aU(this.player.app,6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.fi=this.Qf;g.Pe(this.He,this.ab);this.ab=this.He=null;g.NN.prototype.unload.call(this);g.aU(this.player.app,5);R8(this)};
g.k.X=function(){g.To(this.subscriptions);g.NN.prototype.X.call(this)};
g.k.Ig=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.He.RA.apply(this.He,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.ld};
g.k.IG=function(){return this.loaded?this.He.suggestion:null};
g.k.vg=function(){return this.ab?b8(this.ab).vg:!1};
g.k.hasNext=function(){return this.ab?b8(this.ab).hasNext:!1};
g.k.Xb=function(a,b){this.nA=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.nA};
g.k.getProgressState=function(){var a=b8(this.ab),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.kd():!a.isAdPlaying()&&this.player.kd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+V7(a):a.B,isAtLiveHead:1>=(a.A?a.u+V7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+V7(a):a.u,seekableStart:0<a.C?a.C+
V7(a):a.C}};
g.k.nextVideo=function(){this.ab&&this.ab.nextVideo()};
g.k.ur=function(){this.ab&&this.ab.ur()};
g.k.XK=function(a){1===a&&(this.Jv=this.ab?b8(this.ab):null)};
g.k.XM=function(){var a=E8()?new a8(z8(),void 0):null;if(a){var b=this.fi;this.loaded&&this.unload();this.ab=a;this.Jv=null;b.key!==this.Qf.key&&(this.fi=b,this.load())}else g.Oe(this.ab),this.ab=null,this.loaded&&(this.unload(),(a=this.Jv)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,X7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.rC=function(){this.Si=[this.Qf].concat(qCa());var a=A8()||this.Qf;S8(this,a);this.player.oa("onMdxReceiversChange")};
g.k.VM=function(){var a=A8();S8(this,a)};
g.k.UM=function(){this.fi=A8()};
g.k.tO=function(){this.Jn=!0;R8(this);G8=!1;H8&&C8(H8,1);H8=null};
g.k.sO=function(){this.Jn=!1;R8(this);S8(this,this.Qf);this.fi=this.Qf;G8=!1;H8=null;this.player.playVideo()};
g.k.NH=function(){this.wq=!0;R8(this);g.at("yt-remote-manual-pairing-warning-shown",!0,2592E3);G8=!1;H8&&C8(H8,1);H8=null};
g.k.gd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Si;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?R7():S8(this,b)),this.loaded?this.fi:this.Qf;case "quickCast":return 2===this.Si.length&&"cast-selector-receiver"===this.Si[1].key?(b&&R7(),!0):!1}};
g.k.Ew=function(){this.ab.Ew()};
g.k.dg=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.YN.remote=Q8;})(_yt_player);
